version: '3'
services:
  thyp-sdk:
    build:
      context: ./build
      args:
        username: ${USERNAME}
        password: ${PASSWORD}
        timezone: ${TIMEZONE}
    image: goldenriver/thyp-sdk:${IMAGE_VERSION}
    volumes:
      - "./user_home:/home/${USERNAME}"
    ports:
      - "8022:22"
    networks:
      - developer
    privileged: true 

networks:
  developer:

